/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppChrome {}
}

declare global {


  interface HTMLAppChromeElement extends Components.AppChrome, HTMLStencilElement {}
  var HTMLAppChromeElement: {
    prototype: HTMLAppChromeElement;
    new (): HTMLAppChromeElement;
  };
  interface HTMLElementTagNameMap {
    'app-chrome': HTMLAppChromeElement;
  }
}

declare namespace LocalJSX {
  interface AppChrome extends JSXBase.HTMLAttributes<HTMLAppChromeElement> {}

  interface IntrinsicElements {
    'app-chrome': AppChrome;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


